"""Convert the boot/sleep logo source PNG into a 4-level grayscale C header.

Unlike scripts/convert_icon.py (small 1-bit thresholded UI icons), the logo is
emitted as a single packed 2-bit image: 4 pixels per byte, MSB pair first,
levels 0 (black) to 3 (white) -- the same row layout as Bitmap's 2-bit BMP
path. GfxRenderer::drawImage2Bit decodes it at draw time, rendering the BW
base or a differential grayscale plane depending on the current render mode,
so no pre-expanded per-plane arrays are stored. Content is drawn through
drawPixel, which handles screen orientation; no pre-rotation is needed.

See docs/boot-logo.md for the full regeneration workflow.

The source art is expected to be a circular badge on a black background
(see src/images/Logo256.png). The converter masks everything outside the
badge circle to white and draws a thin black outline ring, because the
badge's own white ring is invisible against the white screen background.
"""

import os
import sys

USAGE = 'Usage: python scripts/convert_logo.py [input.png [size [preview.png]]]'


def find_badge_circle(img):
    """Locate the badge circle: scan the center row/column for the outermost
    bright pixels (the badge's white ring)."""
    width, height = img.size
    bbox = img.point(lambda p: 255 if p > 40 else 0).getbbox()
    if bbox is None:
        sys.exit('error: source image has no bright content')
    cx = (bbox[0] + bbox[2]) / 2
    cy = (bbox[1] + bbox[3]) / 2
    px = img.load()
    row = [x for x in range(width) if px[x, int(cy)] > 40]
    col = [y for y in range(height) if px[int(cx), y] > 40]
    cx = (row[0] + row[-1]) / 2
    cy = (col[0] + col[-1]) / 2
    r = min(row[-1] - row[0], col[-1] - col[0]) / 2
    return cx, cy, r


def build_levels(input_path, size):
    """Return a size x size matrix of gray levels 0 (black) .. 3 (white)."""
    from PIL import Image, ImageDraw

    img = Image.open(input_path)
    if 'A' in img.mode:
        background = Image.new('RGBA', img.size, (255, 255, 255, 255))
        background.paste(img, mask=img.split()[-1])
        img = background
    img = img.convert('L')
    cx, cy, r = find_badge_circle(img)

    # White canvas, paste the source through a circular mask (slightly shrunk
    # so no black background rim survives antialiasing at the edge).
    mask = Image.new('L', img.size, 0)
    ImageDraw.Draw(mask).ellipse([cx - r + 2, cy - r + 2, cx + r - 2, cy + r - 2], fill=255)
    canvas = Image.new('L', img.size, 255)
    canvas.paste(img, (0, 0), mask)

    # Crop square around the circle with a small margin, then downscale.
    side = int(r) + int(r * 0.02)
    crop = canvas.crop((int(cx - side), int(cy - side), int(cx + side), int(cy + side)))
    small = crop.resize((size, size), Image.LANCZOS)

    # Outline ring so the badge keeps a boundary on the white page.
    ring = max(2, round(size / 64))
    ImageDraw.Draw(small).ellipse([ring // 2, ring // 2, size - 1 - ring // 2, size - 1 - ring // 2],
                                  outline=0, width=ring)

    px = small.load()
    return [[min(3, (px[x, y] + 32) // 64) for x in range(size)] for y in range(size)]


def pack_2bit(levels, size):
    data = bytearray()
    for y in range(size):
        for xb in range(size // 4):
            byte = 0
            for i in range(4):
                byte |= levels[y][xb * 4 + i] << (6 - 2 * i)
            data.append(byte)
    return data


def write_preview(levels, size, path):
    from PIL import Image

    recon = Image.new('L', (size, size))
    px = recon.load()
    for y in range(size):
        for x in range(size):
            px[x, y] = levels[y][x] * 85
    recon.resize((size * 2, size * 2), Image.NEAREST).save(path)
    print(f'Wrote {path}')


def main():
    if any(arg in ('-h', '--help') for arg in sys.argv[1:]):
        print(USAGE)
        sys.exit(0)
    if len(sys.argv) > 4:
        print(USAGE)
        sys.exit(1)

    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    input_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(project_root, 'src', 'images', 'Logo256.png')
    size = int(sys.argv[2]) if len(sys.argv) > 2 else 256
    if size % 4 != 0:
        sys.exit('error: size must be a multiple of 4 (pixels are packed 4 per byte)')

    levels = build_levels(input_path, size)
    name = f'Logo{size}'
    data = pack_2bit(levels, size)
    output_path = os.path.join(project_root, 'src', 'images', f'{name}.h')
    with open(output_path, 'w') as f:
        f.write('#pragma once\n#include <cstdint>\n\n')
        f.write('// Generated by scripts/convert_logo.py -- do not edit by hand.\n')
        f.write(f'// Image dimensions: {size}x{size}, packed 2-bit grayscale (4 pixels/byte,\n')
        f.write('// MSB pair first, levels 0=black .. 3=white). Render with\n')
        f.write('// GfxRenderer::drawImage2Bit, which decodes the BW base or a differential\n')
        f.write('// grayscale plane from this data per the current render mode.\n')
        f.write(f'static const uint8_t {name}[] = {{\n')
        vals = [f'0x{b:02x}' for b in data]
        per_line = 19  # 4-space indent + 19 values fits ColumnLimit 120, clang-format stable
        for i in range(0, len(vals), per_line):
            f.write('    ' + ', '.join(vals[i:i + per_line]) + ',\n')
        f.write('};\n')
    print(f'Wrote {output_path} ({len(data)} bytes)')

    if len(sys.argv) > 3:
        write_preview(levels, size, sys.argv[3])


if __name__ == '__main__':
    main()
